Traceback (most recent call last):
  File "orchestration.py", line 213, in <module>
    main()
  File "orchestration.py", line 203, in main
    logging=args.logging,
  File "/Users/sidharthmenon/workspace/classes/6.887/gyoza/models/model.py", line 72, in fit
    wandb.log({"loss:", loss})
  File "/Users/sidharthmenon/.pyenv/versions/gyoza_project/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1314, in log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary